### ISSUE TITLE
war包的代码是服务端的吗？

### ISSUE THREAD

**Issue by SpenserZC** [PiggieGeorge13/GDUTBasketballOrder#1]
就那个war包的，可以发一下吗

**Comment by PiggieGeorge13** [comment]
您好，war包需要部署至tomcat上



---原始邮件---
发件人: "Zhang ***@***.***&gt;
发送时间: 2021年6月23日(周三) 晚上7:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PiggieGeorge13/GDUTBasketballOrder] war包的代码是服务端的吗？ (#1)




 
就那个war包的

**Comment by SpenserZC** [comment]
> 您好，war包需要部署至tomcat上
> […](#)
> ---原始邮件--- 发件人: "Zhang ***@***.***&gt; 发送时间: 2021年6月23日(周三) 晚上7:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [PiggieGeorge13/GDUTBasketballOrder] war包的代码是服务端的吗？ (#1) 就那个war包的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

但是里面有连接数据库的配置。我需要根据代码配下数据库。您这里有代码吗？

**Comment by PiggieGeorge13** [comment]
抱歉，源代码好像已经丢失了，因为这个项目只是用于提交作业用的。

---原始邮件---
发件人: "Zhang ***@***.***&gt;
发送时间: 2021年6月23日(周三) 晚上7:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PiggieGeorge13/GDUTBasketballOrder] war包的代码是服务端的吗？ (#1)




  
您好，war包需要部署至tomcat上
 …
 ---原始邮件--- 发件人: "Zhang @.&gt; 发送时间: 2021年6月23日(周三) 晚上7:21 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [PiggieGeorge13/GDUTBasketballOrder] war包的代码是服务端的吗？ (#1) 就那个war包的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
但是里面有连接数据库的配置。我需要根据代码配下数据库。您这里有代码吗？

**Comment by SpenserZC** [comment]
> 抱歉，源代码好像已经丢失了，因为这个项目只是用于提交作业用的。
> […](#)
> ---原始邮件--- 发件人: "Zhang ***@***.***&gt; 发送时间: 2021年6月23日(周三) 晚上7:42 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [PiggieGeorge13/GDUTBasketballOrder] war包的代码是服务端的吗？ (#1) 您好，war包需要部署至tomcat上 … ---原始邮件--- 发件人: "Zhang @.&gt; 发送时间: 2021年6月23日(周三) 晚上7:21 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [PiggieGeorge13/GDUTBasketballOrder] war包的代码是服务端的吗？ (#1) 就那个war包的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 但是里面有连接数据库的配置。我需要根据代码配下数据库。您这里有代码吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好嘞，没事，还是很感谢了。
